export const thoughtsStrings = {
  sectionTitle: '내 생각',
  placeholder: '이 문장에 대한 생각을 적어보세요',
  addButton: '추가',
  bodyRequired: '내용을 입력해주세요.',
  saveError: '저장하지 못했어요. 다시 시도해주세요.',
  loadError: '불러오지 못했어요.',
  empty: '아직 적은 생각이 없어요.',
  momentTitle: '떠오른 순간',
  momentPlaceholder: '지금 떠오른 생각을 적어보세요',
  unlinkedTitle: '아직 문장에 연결 안 한 생각',
  unlinkedEmpty: '모두 문장에 연결했어요.',
  linkButton: '문장에 연결하기',
  linkPickerTitle: '연결할 문장 선택',
  linkPickerEmpty: '연결할 문장이 없어요. 먼저 문장을 저장해주세요.',
  linkSuccess: '연결했어요!',
  linkError: '연결하지 못했어요. 다시 시도해주세요.',
  cancelButton: '취소',
};
